# Generated by Django 5.0.3 on 2024-06-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='term',
            field=models.DateField(verbose_name='muddati'),
        ),
    ]
