# Generated by Django 5.0.3 on 2024-06-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='app.review'),
        ),
    ]
